### /pay/app/create 创建应用
POST 127.0.0.1:9107/pay/app/create
Content-Type: application/json

{
  "status": 0,
  "name": "demo",
  "remark": "主要填写支付状态回调地址",
  "orderNotifyUrl": "127.0.0.1/pay/demo/update-paid",
  "refundNotifyUrl": "127.0.0.1/pay/demo/update-paid"
}